apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-helloworld
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replica.count }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: flask-helloworld
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

